// Code generated by scratch. You must modify it.

package demo

import (
	context "context"

	desc "gitlab.ozon.ru/newscratch/internal/pb/gitlab.ozon.ru/newscratch/api"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// Ping stub. Please implement it.
func (i *Implementation) Ping(ctx context.Context, req *emptypb.Empty) (*desc.Response, error) {
        return &desc.Response{Message: "Pong"}, nil
}
