// Code generated by scratch. You must modify it.

package demo

import (
	desc "gitlab.ozon.ru/newscratch/internal/pb/gitlab.ozon.ru/newscratch/api"
	scratch "gitlab.ozon.ru/platform/scratch"
)

type Implementation struct {
	desc.UnimplementedDemoServer
}

// NewDemo return new instance of Implementation.
func NewDemo() *Implementation {
	return &Implementation{}
}

// GetDescription is a simple alias to the ServiceDesc constructor.
// It makes it possible to register the service implementation @ the server.
func (i *Implementation) GetDescription() scratch.ServiceDesc {
	return desc.NewDemoServiceDesc(i)
}
